"""empty message

Revision ID: ee27df739bfd
Revises: c397224b92aa
Create Date: 2022-01-18 16:52:42.029816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee27df739bfd'
down_revision = 'c397224b92aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('years_employed', sa.Integer(), nullable=True),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstores.bookstore_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.drop_table('authors')
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_index('bookstores_b_tree_index', table_name='bookstores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('bookstores_b_tree_index', 'bookstores', ['net_yearly_revenue'], unique=False)
    op.add_column('books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['author_id'])
    op.create_table('authors',
    sa.Column('author_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('number_of_books_written', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('author_id', name='authors_pkey')
    )
    op.drop_table('employees')
    # ### end Alembic commands ###
