"""empty message

Revision ID: c397224b92aa
Revises: 8196b7ee2711
Create Date: 2022-01-15 13:03:02.940584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c397224b92aa'
down_revision = '8196b7ee2711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_bookstore_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'bookstore_id')
    op.drop_column('bookstores', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookstores', sa.Column('isbn', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('bookstore_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_bookstore_id_fkey', 'books', 'bookstores', ['bookstore_id'], ['bookstore_id'])
    # ### end Alembic commands ###
