"""empty message

Revision ID: 8196b7ee2711
Revises: 7bc5d3a413d0
Create Date: 2022-01-14 10:42:05.535143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8196b7ee2711'
down_revision = '7bc5d3a413d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_bookstores',
    sa.Column('isbn', sa.BigInteger(), nullable=False),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstores.bookstore_id'], ),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('isbn', 'bookstore_id')
    )
    op.add_column('books', sa.Column('bookstore_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'bookstores', ['bookstore_id'], ['bookstore_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'bookstore_id')
    op.drop_table('books_bookstores')
    # ### end Alembic commands ###
